Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  NODES = {
    "k8s-master" => {
      :ip => "192.168.56.10",
      :memory => 2048,
      :cpus => 2
    },

    "worker-1" => {
      :ip => "192.168.56.11",
      :memory => 1024,
      :cpus => 1
    },

    "worker-2" => {
      :ip => "192.168.56.12",
      :memory => 1024,
      :cpus => 1
    }
  }

  NODES.each do |name, config_data|

    config.vm.define name do |node|

      node.vm.hostname = name

      node.vm.network "private_network",
        ip: config_data[:ip]

      # ---------------------------------
      # Bootstrap provisioning
      # ---------------------------------
      node.vm.provision "shell",
        path: "scripts/bootstrap.sh"

      # ---------------------------------
      # VirtualBox configuration
      # ---------------------------------
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = config_data[:memory]
        vb.cpus = config_data[:cpus]
      end

    end
  end
end
