---
- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure Kubernetes networking parameters
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
