---
- name: Configure kubelet node IP
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
