---
- name: Copy join command from master
  fetch:
    src: /tmp/kubernetes_join_command.sh
    dest: /tmp/kubernetes_join_command.sh
    flat: yes
  delegate_to: k8s-master

- name: Copy join command to worker
  copy:
    src: /tmp/kubernetes_join_command.sh
    dest: /tmp/kubernetes_join_command.sh
    mode: '0777'

- name: Join worker node to cluster
  command: sh /tmp/kubernetes_join_command.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
